=== anapopescu-beep/audi_sandbox/Components/Application/Autoliv/NVP/Config/NVP_Layout/Calibration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Calibration (Nb_Block,Block+) >
<!ELEMENT Nb_Block (#PCDATA) >
<!ELEMENT Block (Name_of_Block,Address_of_Block,ID,CKS,Nb_Variable,Size_of_Block,Variable+) >
<!ELEMENT Name_of_Block (#PCDATA) >
<!ELEMENT Address_of_Block (#PCDATA) >
<!ELEMENT ID (#PCDATA) >
<!ELEMENT CKS (#PCDATA) >
<!ELEMENT Nb_Variable (#PCDATA) >
<!ELEMENT Size_of_Block (#PCDATA) >
<!ELEMENT Variable (Alias_In_RAM,Type_of_Variable,Array,NB_Data,Address_of_Variable,Data+) >
<!ELEMENT Alias_In_RAM (#PCDATA) >
<!ELEMENT Type_of_Variable (#PCDATA) >
<!ELEMENT Array (#PCDATA) >
<!ELEMENT NB_Data (#PCDATA) >
<!ELEMENT Address_of_Variable (#PCDATA) >
<!ELEMENT Data (Value,Unit,Description,Low_Range,High_Range,Requirement) >
<!ELEMENT Value (#PCDATA) >
<!ELEMENT Unit (#PCDATA) >
<!ELEMENT Description (#PCDATA) >
<!ELEMENT Low_Range (#PCDATA) >
<!ELEMENT High_Range (#PCDATA) >
<!ELEMENT Requirement (#PCDATA) >

=== anapopescu-beep/audi_sandbox/Components/Application/Autoliv/NVP/Config/NVP_Layout/Calibration.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Calibration SYSTEM "Calibration.dtd">
<Calibration>
    <Nb_Block>4</Nb_Block>
    <Block>
        <Name_of_Block>CAL_NTC_LUT</Name_of_Block>
        <Address_of_Block>000FE000</Address_of_Block>
        <ID>0</ID>
        <CKS>None</CKS>
        <Nb_Variable>2</Nb_Variable>
        <Size_of_Block>40</Size_of_Block>
        <Variable>
            <Alias_In_RAM>CAL_au16TempAdcLsb</Alias_In_RAM>
            <Type_of_Variable>uint16</Type_of_Variable>
            <Array>True</Array>
            <NB_Data>10</NB_Data>
            <Address_of_Variable>000FE000</Address_of_Variable>
            <Data>
                <Value>0019</Value>
                <Unit>lsb</Unit>
                <Description>ADC value</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement>DOM_eCS_TF_J_303</Requirement>
            </Data>
            <Data>
                <Value>0036</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>0074</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>00F7</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>02AE</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>0331</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>037D</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>03AA</Value>
                <Unit>lsb</Unit>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>3FF</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>03C8</Value>
                <Unit/>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>0</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>03DB</Value>
                <Unit/>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>0</High_Range>
                <Requirement/>
            </Data>
        </Variable>
        <Variable>
            <Alias_In_RAM>CAL_au16TempInDeg</Alias_In_RAM>
            <Type_of_Variable>uint16</Type_of_Variable>
            <Array>True</Array>
            <NB_Data>10</NB_Data>
            <Address_of_Variable>000FE014</Address_of_Variable>
            <Data>
                <Value>0000</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement>DOM_eCS_TF_J_305</Requirement>
            </Data>
            <Data>
                <Value>037A</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>07A8</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>0CD0</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>19AA</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>1F4A</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>2468</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>2922</Value>
                <Unit>°C</Unit>
                <Description>Resolution: 0.125</Description>
                <Low_Range>0000</Low_Range>
                <High_Range>3E8</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>2E40</Value>
                <Unit/>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>0</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>3386</Value>
                <Unit/>
                <Description/>
                <Low_Range>0000</Low_Range>
                <High_Range>0</High_Range>
                <Requirement/>
            </Data>
        </Variable>
    </Block>
    <Block>
        <Name_of_Block>CAL_APP_CONFIG</Name_of_Block>
        <Address_of_Block>000FE028</Address_of_Block>
        <ID>1</ID>
        <CKS>None</CKS>
        <Nb_Variable>2</Nb_Variable>
        <Size_of_Block>2</Size_of_Block>
        <Variable>
            <Alias_In_RAM>NVP_Gliwa_Enable</Alias_In_RAM>
            <Type_of_Variable>uint8</Type_of_Variable>
            <Array>False</Array>
            <NB_Data>1</NB_Data>
            <Address_of_Variable>000FE028</Address_of_Variable>
            <Data>
                <Value>55</Value>
                <Unit/>
                <Description>Enables or Disables the Gliwa T1 software</Description>
                <Low_Range>00</Low_Range>
                <High_Range>0</High_Range>
                <Requirement>DOM_eCS_TF_J_315</Requirement>
            </Data>
        </Variable>
        <Variable>
            <Alias_In_RAM>NVP_Gliwa_Flex_Enable</Alias_In_RAM>
            <Type_of_Variable>uint8</Type_of_Variable>
            <Array>False</Array>
            <NB_Data>1</NB_Data>
            <Address_of_Variable>000FE029</Address_of_Variable>
            <Data>
                <Value>55</Value>
                <Unit/>
                <Description>Enables or disables the Gliwa flex plugin</Description>
                <Low_Range>00</Low_Range>
                <High_Range>0</High_Range>
                <Requirement>DOM_eCS_TF_J_317</Requirement>
            </Data>
        </Variable>
    </Block>
    <Block>
        <Name_of_Block>CAL_PTC_RES_TO_TEMP_LOOKUP_TABLE</Name_of_Block>
        <Address_of_Block>000FE02C</Address_of_Block>
        <ID>2</ID>
        <CKS>None</CKS>
        <Nb_Variable>2</Nb_Variable>
        <Size_of_Block>136</Size_of_Block>
        <Variable>
            <Alias_In_RAM>NVP_as16PTCTemp</Alias_In_RAM>
            <Type_of_Variable>sint16</Type_of_Variable>
            <Array>True</Array>
            <NB_Data>34</NB_Data>
            <Address_of_Variable>000FE02C</Address_of_Variable>
            <Data>
                <Value>FFD8</Value>
                <Unit>°C</Unit>
                <Description>Temperature of sensor in degrees</Description>
                <Low_Range>FFD8</Low_Range>
                <High_Range>007D</High_Range>
                <Requirement>DOM_eCS_TF_J_538</Requirement>
            </Data>
            <Data>
                <Value>FFDD</Value>
                <Unit>°C</Unit>
                <Description>Temperature of sensor in degrees</Description>
                <Low_Range>FFD8</Low_Range>
                <High_Range>007D</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>FFE2</Value>
                <Unit>°C</Unit>
                <Description>Temperature of sensor in degrees</Description>
                <Low_Range>FFD8</Low_Range>
                <High_Range>007D</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>FFE7</Value>
                <Unit>°C</Unit>
                <Description>Temperature of sensor in degrees</Description>
                <Low_Range>FFD8</Low_Range>
                <High_Range>007D</High_Range>
                <Requirement/>
            </Data>
            <Data>
                <Value>FFEC</Value>
                <Unit>°C</Unit>
                <Description>Temperature of sensor in degrees</Description>
                <Low_Range>FFD8</Low_Range>
                <High_Range>007D</High_Range>
                <Requirement/>
            </Data>
            <Data>
