=== anapopescu-beep/audi_sandbox/Components/Application/Autoliv/NVP/Config/NVP_Layout/GlobalConfiguration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT GlobalConfiguration (ApplicationName,StartAddress,Version, Version,MemorySize) >
<!ELEMENT ApplicationName (#PCDATA) >
<!ELEMENT StartAddress (Calibration,RamShadow,ROM,EepromAlias,EepromAliasId) >
<!ELEMENT Calibration (#PCDATA) >
<!ELEMENT RamShadow (#PCDATA) >
<!ELEMENT ROM (#PCDATA) >
<!ELEMENT EepromAlias (#PCDATA) >
<!ELEMENT EepromAliasId (#PCDATA) >
<!ELEMENT Version (Major,Minor,Subversion) >
<!ATTLIST Version name CDATA "">
<!ELEMENT Major (#PCDATA) >
<!ELEMENT Minor (#PCDATA) >
<!ELEMENT Subversion (#PCDATA) >
<!ELEMENT MemorySize (CalibrationSize,RomSize) >
<!ELEMENT CalibrationSize (#PCDATA) >
<!ELEMENT RomSize (#PCDATA) >

=== anapopescu-beep/audi_sandbox/Components/Application/Autoliv/NVP/Config/NVP_Layout/GlobalConfiguration.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GlobalConfiguration SYSTEM "GlobalConfiguration.dtd">
<GlobalConfiguration>
    <ApplicationName>Application</ApplicationName>
    <StartAddress>
        <Calibration>000FE000</Calibration>
        <RamShadow>14000000</RamShadow>
        <ROM>000FF000</ROM>
        <EepromAlias>EE010000</EepromAlias>
        <EepromAliasId>3</EepromAliasId>
    </StartAddress>
    <Version name="Calib">
        <Major>1</Major>
        <Minor>1</Minor>
        <Subversion>1</Subversion>
    </Version>
    <Version name="E2P">
        <Major>1</Major>
        <Minor>1</Minor>
        <Subversion>1</Subversion>
    </Version>
    <MemorySize>
        <CalibrationSize>4096</CalibrationSize>
        <RomSize>4096</RomSize>
    </MemorySize>
</GlobalConfiguration>
