=== anapopescu-beep/audi_sandbox/Tools/NVP_Layout/Config/Config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ConfigPath (VirtualDrive,WorkspacePath,DataFile,GenerationScript,ProjectType,TresosIncludeFile,TresosSourceFile) >
<!ELEMENT VirtualDrive (#PCDATA) >
<!ELEMENT WorkspacePath (#PCDATA) >
<!ELEMENT DataFile (#PCDATA) >
<!ELEMENT GenerationScript (#PCDATA) >
<!ELEMENT ProjectType (#PCDATA) >
<!ELEMENT TresosIncludeFile (#PCDATA) >
<!ELEMENT TresosSourceFile (#PCDATA) >

=== anapopescu-beep/audi_sandbox/Tools/NVP_Layout/Config/Config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ConfigPath SYSTEM "Config.dtd">
<ConfigPath>
	<VirtualDrive>..\\..\\..\\</VirtualDrive>
	<WorkspacePath>Tools\\NVP_Layout\\</WorkspacePath>
	<DataFile>Components\\Application\\Autoliv\\NVP\\Config\\NVP_Layout\\</DataFile>
	<GenerationScript>Components\\Application\\Autoliv\\NVP\\Scripts\\</GenerationScript>
	<ProjectType>extended</ProjectType>
	<TresosIncludeFile>Components\\Application\\Supplier\\Tresos_Configuration_8.5.1\\Workspace\\Application\\Tresos_BSW_generated\\include\\</TresosIncludeFile>
	<TresosSourceFile>Components\\Application\\Supplier\\Tresos_Configuration_8.5.1\\Workspace\\Application\\Tresos_BSW_generated\\src\\</TresosSourceFile>
</ConfigPath>
